import os
from pathlib import Path
import subprocess
import tempfile
import unittest


SKILL_DIR = Path(__file__).resolve().parents[1]
RELEASE_ORDER = SKILL_DIR / "scripts" / "release-order"
PACT_GRAPH = SKILL_DIR / "scripts" / "pact-graph"


class ReleaseOrderTest(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.root = Path(self.temp_dir.name)
        (self.root / ".git").mkdir()

    def tearDown(self):
        self.temp_dir.cleanup()

    def run_order(self, *args, cwd=None):
        return subprocess.run(
            [str(RELEASE_ORDER), *args],
            cwd=cwd or self.root,
            text=True,
            capture_output=True,
            check=False,
        )

    def write_manifest(self, body):
        docs = self.root / "docs"
        docs.mkdir(exist_ok=True)
        (docs / "release-manifest.yaml").write_text(body, encoding="utf-8")

    def write_pact(self, consumer, provider):
        path = self.root / provider / "src" / "test" / "resources" / "pacts"
        path.mkdir(parents=True, exist_ok=True)
        (path / f"{consumer}-consumer-{provider}-provider.json").write_text("{}", encoding="utf-8")

    def test_no_manifest_or_pacts_means_no_ordering(self):
        nested = self.root / "services" / "web"
        nested.mkdir(parents=True)

        result = self.run_order(cwd=nested)

        self.assertEqual(0, result.returncode, result.stderr)
        self.assertIn("provider=none", result.stdout)
        self.assertIn("manifest=absent", result.stdout)
        self.assertIn("status: not-applicable (no ordering configured)", result.stdout)
        self.assertEqual([], graph_lines(result.stdout))

        write_result = self.run_order("--write")
        self.assertNotEqual(0, write_result.returncode)
        self.assertIn("pact provider is not active", write_result.stderr)

    def test_manifest_manual_order_works_without_pacts(self):
        self.write_manifest(
            """# Example marker text outside order.derived is not provider configuration.
# >>> GENERATED by scripts/pact-graph
# <<< END GENERATED
order:
  manual:
    web: [api, database]
    worker: [queue]
  suppress:
    web: [database]
"""
        )

        result = self.run_order()

        self.assertEqual(0, result.returncode, result.stderr)
        self.assertIn("provider=manifest", result.stdout)
        self.assertEqual(["web: [api]", "worker: [queue]"], graph_lines(result.stdout))
        self.assertIn("status: not-applicable (manifest-declared)", result.stdout)

        write_result = self.run_order("--write")
        self.assertNotEqual(0, write_result.returncode)
        self.assertIn("pact provider is not active", write_result.stderr)

    def test_pact_provider_merges_manual_and_applies_suppressions(self):
        self.write_pact("web", "api")
        self.write_pact("web", "legacy")
        self.write_manifest(
            """order:
  derived:
    # >>> GENERATED by scripts/pact-graph — do not hand-edit (release-manager rewrites)
    web: [api,legacy]
    # <<< END GENERATED
  manual:
    worker: [queue]
  suppress:
    web: [legacy]
"""
        )

        result = self.run_order()

        self.assertEqual(0, result.returncode, result.stderr)
        self.assertIn("provider=pact", result.stdout)
        self.assertEqual(["web: [api]", "worker: [queue]"], graph_lines(result.stdout))
        self.assertIn("status: in-sync", result.stdout)

    def test_pact_provider_without_manifest_is_read_only_and_unmanaged(self):
        self.write_pact("web", "api")

        result = self.run_order()

        self.assertEqual(0, result.returncode, result.stderr)
        self.assertIn("provider=pact", result.stdout)
        self.assertEqual(["web: [api]"], graph_lines(result.stdout))
        self.assertIn("status: unmanaged (no release manifest)", result.stdout)

        write_result = self.run_order("--write")
        self.assertNotEqual(0, write_result.returncode)
        self.assertIn("cannot reconcile without docs/release-manifest.yaml", write_result.stderr)

    def test_generated_block_keeps_pact_provider_active_after_last_edge_is_removed(self):
        self.write_manifest(
            """order:
  derived:
    # >>> GENERATED by scripts/pact-graph — do not hand-edit (release-manager rewrites)
    web: [legacy]
    # <<< END GENERATED
  manual: {}
  suppress: []
"""
        )

        before = self.run_order()
        write_result = self.run_order("--write")
        after = self.run_order()

        self.assertEqual(0, before.returncode, before.stderr)
        self.assertIn("provider=pact", before.stdout)
        self.assertIn("graph=generated", before.stdout)
        self.assertEqual(["web: [legacy]"], graph_lines(before.stdout))
        self.assertIn("removed: web -> legacy", before.stdout)
        self.assertEqual(0, write_result.returncode, write_result.stderr)
        self.assertIn("---WRITE---\nok", write_result.stdout)
        self.assertEqual(0, after.returncode, after.stderr)
        self.assertIn("provider=pact", after.stdout)
        self.assertIn("status: in-sync", after.stdout)
        self.assertEqual([], graph_lines(after.stdout))

    def test_invalid_nonempty_inline_manual_map_fails_clearly(self):
        self.write_manifest("order:\n  manual: {web: [api]}\n")

        result = self.run_order()

        self.assertEqual(2, result.returncode)
        self.assertIn("use a block map", result.stderr)

    def test_pact_graph_accepts_generic_git_project_root(self):
        self.write_pact("web", "api")

        result = subprocess.run(
            [str(PACT_GRAPH)],
            cwd=self.root,
            text=True,
            capture_output=True,
            check=False,
            env={key: value for key, value in os.environ.items() if key != "RELEASE_PROJECT_ROOT"},
        )

        self.assertEqual(0, result.returncode, result.stderr)
        self.assertIn("web: [api]", result.stdout)


def graph_lines(output):
    lines = output.splitlines()
    start = lines.index("---GRAPH---") + 1
    end = lines.index("---DRIFT---")
    return lines[start:end]


if __name__ == "__main__":
    unittest.main()
