"""Read-only cleanup inventory and refusal boundaries."""
from contextlib import redirect_stdout
import importlib.util
import io
import json
import os
from pathlib import Path
import subprocess
import tempfile
import unittest
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[3]
HELPER = ROOT / "skills/beads/scripts/integration_cleanup.py"
BLOCK = "<!-- BEGIN BEADS INTEGRATION v:1 profile:minimal hash:fixture -->\ngenerated\n<!-- END BEADS INTEGRATION -->\n"
CODEX = "<!-- BEGIN BEADS CODEX SETUP: generated by bd setup codex -->\ngenerated\n<!-- END BEADS CODEX SETUP -->\n"
HOOK = "# --- BEGIN BEADS INTEGRATION v1.2.2 ---\nbd hooks run pre-commit\n# --- END BEADS INTEGRATION v1.2.2 ---\n"


class InventoryTests(unittest.TestCase):
    def setUp(self):
        self.assertTrue(HELPER.is_file(), "read-only integration cleanup helper is not implemented")
        spec = importlib.util.spec_from_file_location("integration_cleanup", HELPER)
        self.helper = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(self.helper)
        (ROOT / ".artifacts").mkdir(exist_ok=True)
        self.temp = tempfile.TemporaryDirectory(dir=ROOT / ".artifacts", prefix="cleanup-test-")
        self.addCleanup(self.temp.cleanup)
        self.base = Path(self.temp.name)
        self.repo = self.base / "repo"
        self.repo.mkdir()
        self.env = patch.dict(os.environ, {"GIT_CONFIG_NOSYSTEM": "1", "GIT_CONFIG_GLOBAL": os.devnull, "GIT_CONFIG_COUNT": "0"})
        self.env.start()
        self.addCleanup(self.env.stop)
        subprocess.run(["git", "init", "-q", "-b", "main", str(self.repo)], check=True)
        self.probe = patch.object(self.helper, "bd_probe", return_value={
            "version": "1.2.2", "supported": True, "executable": "/trusted/bd", "sha256": "a" * 64,
        })
        self.probe.start()
        self.addCleanup(self.probe.stop)

    def put(self, path, value):
        target = self.repo / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(value)
        return target

    def inspect(self):
        return self.helper.inspect_repository(str(self.repo))

    def action(self, report, name):
        return next(item for item in report["actions"] if item["id"] == name)

    def snapshot(self):
        return {str(p.relative_to(self.repo)): (p.lstat().st_mode, p.read_bytes())
                for p in self.repo.rglob("*") if p.is_file() and not p.is_symlink()}

    def test_clean_inspection_is_a_read_only_noop(self):
        self.put("AGENTS.md", "authored policy\n")
        before = self.snapshot()
        first = self.inspect()
        self.assertEqual({a["status"] for a in first["actions"]}, {"clean"})
        self.assertEqual(self.inspect()["fingerprint"], first["fingerprint"])
        self.assertEqual(before, self.snapshot())

    def test_claude_mixed_hooks_and_authored_text_have_exact_scoped_proposal(self):
        self.put("CLAUDE.md", "before\n" + BLOCK + "after\n")
        self.put("AGENTS.md", "authored\n" + BLOCK)
        self.put(".claude/settings.json", json.dumps({"private": "DO_NOT_PRINT_ME", "hooks": {
            "SessionStart": [{"hooks": [{"type": "command", "command": "bd prime --hook-json"},
                                         {"type": "command", "command": "project-check"}]}]}}))
        before = self.snapshot()
        report = self.inspect()
        action = self.action(report, "claude")
        self.assertEqual(action["status"], "ready")
        self.assertIn("--global=false", action["argv"])
        self.assertIn(str(self.repo), action["argv"])
        self.assertEqual({e["path"] for e in action["effects"]}, {"CLAUDE.md", ".claude/settings.json"})
        self.assertEqual(self.action(report, "agents-blocks")["status"], "ready")
        self.assertNotIn("DO_NOT_PRINT_ME", json.dumps(report))
        self.assertEqual(before, self.snapshot())

    def test_aliases_are_inventoried_once_but_native_mutation_is_refused(self):
        self.put("AGENTS.md", BLOCK)
        (self.repo / "CLAUDE.md").symlink_to("AGENTS.md")
        report = self.inspect()
        groups = [f for f in report["files"] if "AGENTS.md" in f["aliases"]]
        self.assertEqual(len(groups), 1)
        self.assertEqual(set(groups[0]["aliases"]), {"AGENTS.md", "CLAUDE.md"})
        self.assertEqual(self.action(report, "claude")["status"], "blocked")
        self.assertTrue((self.repo / "CLAUDE.md").is_symlink())

    def test_outside_links_and_symlinked_parent_are_not_read_or_proposed(self):
        outside = self.base / "private"
        outside.mkdir()
        (outside / "settings.json").write_text("DO_NOT_PRINT_ME")
        (self.repo / ".claude").symlink_to(outside)
        self.put("CLAUDE.md", BLOCK)
        report = self.inspect()
        self.assertEqual(self.action(report, "claude")["status"], "blocked")
        self.assertNotIn("DO_NOT_PRINT_ME", json.dumps(report))

    def test_hardlinks_and_malformed_or_oversized_inputs_fail_closed(self):
        for mode in ("hardlink", "markers", "json", "oversized", "duplicate-json"):
            with self.subTest(mode=mode):
                a = self.put("CLAUDE.md", BLOCK)
                settings = self.repo / ".claude/settings.json"
                if settings.exists():
                    settings.unlink()
                if mode == "hardlink":
                    os.link(a, self.repo / "alias")
                elif mode == "markers":
                    a.write_text(BLOCK + BLOCK)
                elif mode == "json":
                    self.put(".claude/settings.json", "{")
                elif mode == "duplicate-json":
                    self.put(".claude/settings.json", '{"hooks":{},"hooks":{}}')
                else:
                    a.write_text("x" * (self.helper.MAX_BYTES + 1))
                self.assertEqual(self.action(self.inspect(), "claude")["status"], "blocked")
                if mode == "hardlink":
                    (self.repo / "alias").unlink()

    def test_codex_refuses_shared_flags_and_mixed_command_entries(self):
        self.put("AGENTS.md", CODEX)
        self.put(".codex/config.toml", "[features]\nhooks=true\n")
        self.assertEqual(self.action(self.inspect(), "codex-native")["status"], "blocked")
        (self.repo / ".codex/config.toml").unlink()
        self.put(".codex/hooks.json", json.dumps({"hooks": {"SessionStart": [{"hooks": [
            {"type": "command", "command": "bd codex-hook SessionStart"},
            {"type": "command", "command": "project-check"},
        ]}]}}))
        self.assertEqual(self.action(self.inspect(), "codex-native")["status"], "blocked")

    def test_exact_generated_codex_tree_is_ready_for_bounded_deletion(self):
        files = {
            ".codex/config.toml": b"generated config",
            ".codex/hooks.json": b"generated hooks",
            ".agents/skills/beads/SKILL.md": b"generated skill",
            ".agents/skills/beads/agents/openai.yaml": b"generated metadata",
        }
        self.put("AGENTS.md", "authored\n")
        for path, content in files.items():
            target = self.repo / path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(content)
        hashes = {path: self.helper.digest(content) for path, content in files.items()}
        with patch.object(self.helper, "GENERATED_CODEX_HASHES", hashes):
            report = self.inspect()
            action = self.action(report, "codex-generated")
            self.assertEqual(action["status"], "ready")
            self.assertEqual({effect["path"] for effect in action["effects"]}, set(files))
            self.put(".codex/authored.toml", "keep")
            self.assertEqual(self.action(self.inspect(), "codex-generated")["status"], "blocked")

    def test_agent_blocks_are_ready_for_exact_marker_bounded_edit(self):
        self.put("AGENTS.md", "before\n" + BLOCK + "\n" + CODEX + "after\n")
        action = self.action(self.inspect(), "agents-blocks")
        self.assertEqual(action["status"], "ready")
        self.assertEqual([effect["operation"] for effect in action["effects"]], [
            "remove exact general managed block", "remove exact Codex managed block",
        ])

    def test_interactions_requires_ignore_edit_and_index_only_removal(self):
        self.put(".gitignore", "# project\n")
        interactions = self.put(".beads/interactions.jsonl", "")
        subprocess.run(["git", "-C", str(self.repo), "add", ".gitignore", ".beads/interactions.jsonl"], check=True)
        action = self.action(self.inspect(), "interactions-ignore")
        self.assertEqual(action["status"], "ready")
        self.assertEqual(action["ignoreRule"], "/.beads/interactions.jsonl")
        self.assertTrue(interactions.exists())
        tracked = subprocess.run(["git", "-C", str(self.repo), "ls-files", ".beads/interactions.jsonl"], capture_output=True, text=True, check=True).stdout.strip()
        self.assertEqual(tracked, ".beads/interactions.jsonl")

    def test_interactions_already_untracked_and_ignored_is_clean(self):
        self.put(".gitignore", "/.beads/interactions.jsonl\n")
        self.put(".beads/interactions.jsonl", "local\n")
        self.assertEqual(self.action(self.inspect(), "interactions-ignore")["status"], "clean")

    def test_codex_ready_only_without_shared_config_or_unproven_skill_ownership(self):
        self.put("AGENTS.md", "authored\n" + CODEX)
        self.assertEqual(self.action(self.inspect(), "codex-native")["status"], "ready")
        self.put(".agents/skills/beads/SKILL.md", "authored skill")
        self.assertEqual(self.action(self.inspect(), "codex-native")["status"], "blocked")

    def test_hooks_preserve_default_path_logic_but_refuse_shared_path_checks(self):
        self.put(".git/hooks/pre-commit", "#!/bin/sh\n" + HOOK + "\nproject-check\n")
        self.assertEqual(self.action(self.inspect(), "hooks")["status"], "ready")
        self.put(".beads/hooks/pre-commit", "#!/bin/sh\n" + HOOK + "\nproject-check\n")
        subprocess.run(["git", "-C", str(self.repo), "config", "core.hooksPath", ".beads/hooks"], check=True)
        self.assertEqual(self.action(self.inspect(), "hooks")["status"], "blocked")

    def test_noncanonical_beads_hookspath_cannot_claim_native_reset(self):
        self.put(".beads/hooks/pre-commit", "#!/bin/sh\n" + HOOK)
        subprocess.run(["git", "-C", str(self.repo), "config", "core.hooksPath", ".beads/./hooks"], check=True)
        self.assertEqual(self.action(self.inspect(), "hooks")["status"], "blocked")

    def test_hooks_refuse_chain_backups_and_global_fallback(self):
        self.put(".git/hooks/pre-commit", "#!/bin/sh\n" + HOOK)
        self.put(".git/hooks/pre-commit.old", "project-check")
        self.assertEqual(self.action(self.inspect(), "hooks")["status"], "blocked")
        (self.repo / ".git/hooks/pre-commit.old").unlink()
        global_config = self.base / "global.gitconfig"
        global_config.write_text("[core]\n hooksPath = /outside/hooks\n")
        with patch.dict(os.environ, {"GIT_CONFIG_GLOBAL": str(global_config)}):
            self.assertEqual(self.action(self.inspect(), "hooks")["status"], "blocked")

    def test_stale_fingerprint_detects_content_and_topology_changes(self):
        self.put("CLAUDE.md", BLOCK)
        initial = self.inspect()["fingerprint"]
        self.put("CLAUDE.md", "authored\n" + BLOCK)
        self.assertNotEqual(initial, self.inspect()["fingerprint"])
        initial = self.inspect()["fingerprint"]
        (self.repo / "CLAUDE.md").chmod(0o600)
        self.assertNotEqual(initial, self.inspect()["fingerprint"])

    def test_unknown_bd_version_and_local_config_includes_are_inventory_only(self):
        self.put("CLAUDE.md", BLOCK)
        with patch.object(self.helper, "bd_probe", return_value={"version": "future", "supported": False}):
            self.assertEqual(self.action(self.inspect(), "claude")["status"], "blocked")
        subprocess.run(["git", "-C", str(self.repo), "config", "include.path", "/unknown/config"], check=True)
        self.assertEqual(self.action(self.inspect(), "claude")["status"], "blocked")

    def test_shared_config_and_redirected_beads_are_never_proposed(self):
        self.put("CLAUDE.md", BLOCK)
        config = self.repo / ".git/config"
        saved = config.read_text()
        config.unlink()
        outside = self.base / "external-config"
        outside.write_text(saved)
        config.symlink_to(outside)
        self.assertEqual(self.action(self.inspect(), "claude")["status"], "blocked")
        config.unlink()
        config.write_text(saved)
        self.put(".beads/redirect", "/another/store\n")
        self.assertEqual(self.action(self.inspect(), "claude")["status"], "blocked")

    def test_cli_rejects_stale_or_ineligible_selection_without_writes(self):
        self.put("CLAUDE.md", BLOCK)
        before = self.snapshot()
        with patch("sys.argv", [str(HELPER), "--repo", str(self.repo), "--expect", "stale"]), redirect_stdout(io.StringIO()) as out:
            self.assertEqual(self.helper.main(), 2)
        self.assertIn("stale", out.getvalue())
        with patch("sys.argv", [str(HELPER), "--repo", str(self.repo), "--action", "codex-native"]), redirect_stdout(io.StringIO()):
            self.assertEqual(self.helper.main(), 2)
        self.assertEqual(before, self.snapshot())

    def test_ambient_config_allows_only_noninteractive_credential_suppression(self):
        with patch.dict(os.environ, {"GIT_CONFIG_COUNT": "1", "GIT_CONFIG_KEY_0": "credential.interactive", "GIT_CONFIG_VALUE_0": "false"}):
            self.assertTrue(self.inspect()["readOnly"])
        with patch.dict(os.environ, {"GIT_CONFIG_COUNT": "1", "GIT_CONFIG_KEY_0": "core.hooksPath", "GIT_CONFIG_VALUE_0": "/outside"}):
            with self.assertRaises(ValueError):
                self.inspect()

    def test_subdirectories_and_shared_worktree_administration_are_refused(self):
        child = self.repo / "child"
        child.mkdir()
        with self.assertRaises(ValueError):
            self.helper.inspect_repository(str(child))
        self.put("CLAUDE.md", BLOCK)
        (self.repo / ".git/worktrees/peer").mkdir(parents=True)
        self.assertEqual(self.action(self.inspect(), "claude")["status"], "blocked")
