#!/usr/bin/env python3
"""Read-only, fail-closed preview of three bd 1.2.2 project removal commands."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import stat
import subprocess
import sys

MAX_BYTES = 262144
MAX_HOOK_FILES = 128
HOOK_NAMES = ("pre-commit", "post-merge", "pre-push", "post-checkout", "prepare-commit-msg")
CLAUDE_COMMANDS = {"bd prime", "bd prime --stealth", "bd prime --hook-json", "bd prime --stealth --hook-json"}
CODEX_EVENTS = ("SessionStart", "PreCompact", "PostCompact", "UserPromptSubmit")
GENERATED_CODEX_HASHES = {
    ".codex/config.toml": "d37497c3278121598a663564ab38b53f658969717f78decb661ddd11c66551ea",
    ".codex/hooks.json": "c4221cf355ce715e49b250d02455a4f14accaf4fc133979bfedf4b1f99660d90",
    ".agents/skills/beads/SKILL.md": "1a621606cfa9a14cbacff84bf5c496b4c2c175c2df329e8d19d4e01fc989dedd",
    ".agents/skills/beads/agents/openai.yaml": "c7ff618a9a6bcce71b25f722f67861b7685651d08fb72d8fff7d947aac403718",
}
TEMPLATE_HASHES = {path: value for path, value in GENERATED_CODEX_HASHES.items() if path.startswith(".agents/")}
IGNORE_INTERACTIONS = "/.beads/interactions.jsonl"
GENERATED_CODEX_BLOCK_SHA256 = "6089c5aad13d2440f0034a57e2c8085ec72b28ce0ec1169ce4277ed76f826936"
MARKERS = {
    "general": (r"<!-- BEGIN BEADS INTEGRATION(?: v:[^\r\n]*?)? -->", "<!-- END BEADS INTEGRATION -->"),
    "codex": ("<!-- BEGIN BEADS CODEX SETUP: generated by bd setup codex -->", "<!-- END BEADS CODEX SETUP -->"),
    "hook": (r"# --- BEGIN BEADS INTEGRATION v1\.2\.2 ---", "# --- END BEADS INTEGRATION v1.2.2 ---"),
}


def digest(data):
    return hashlib.sha256(data).hexdigest()


def execute(argv, cwd=None, allowed=(0,)):
    env = dict(os.environ, GIT_OPTIONAL_LOCKS="0", BD_DISABLE_METRICS="1", BD_DISABLE_EVENT_FLUSH="1")
    result = subprocess.run(argv, cwd=cwd, env=env, capture_output=True, timeout=10, check=False)
    if result.returncode not in allowed or len(result.stdout) > MAX_BYTES or len(result.stderr) > MAX_BYTES:
        raise ValueError("read-only command failed or exceeded its output bound: " + Path(argv[0]).name)
    return result.stdout.decode("utf-8", errors="strict").strip()


def git(root, *args, allowed=(0,)):
    return execute(["git", "-c", "core.fsmonitor=false", "-C", str(root), *args], allowed=allowed)


def bd_probe():
    binary = shutil.which("bd")
    if not binary:
        return {"supported": False, "reason": "bd unavailable"}
    binary = str(Path(binary).resolve(strict=True))
    try:
        version = execute([binary, "--version"])
        version_match = re.match(r"^bd version (\S+)", version)
        supported = bool(version_match and version_match[1] == "1.2.2")
        for command, tokens in [
            (["init", "--help"], ["--skip-agents", "--skip-hooks"]),
            (["setup", "--help"], ["--remove", "--global"]),
            (["hooks", "uninstall", "--help"], ["Remove bd git hooks", "uninstall"]),
        ]:
            help_text = execute([binary, *command])
            supported = supported and all(token in help_text for token in tokens)
        env_binary = shutil.which("env")
        if not env_binary or "--chdir" not in execute([env_binary, "--help"]):
            supported = False
        with open(binary, "rb") as stream:
            hasher = hashlib.sha256()
            for chunk in iter(lambda: stream.read(65536), b""):
                hasher.update(chunk)
        return {"executable": binary, "version": version_match[1] if version_match else "unknown",
                "sha256": hasher.hexdigest(), "envExecutable": str(Path(env_binary).resolve()) if env_binary else None,
                "supported": supported}
    except (OSError, ValueError, subprocess.SubprocessError):
        return {"executable": binary, "supported": False, "reason": "bd version/help probe unavailable"}


def block_ranges(text, kind):
    begin, end = MARKERS[kind]
    begins = list(re.finditer("^" + begin + r"\r?$", text, re.MULTILINE))
    ends = list(re.finditer("^" + re.escape(end) + r"\r?$", text, re.MULTILINE))
    prefix = {"general": "<!-- BEGIN BEADS INTEGRATION", "codex": "<!-- BEGIN BEADS CODEX", "hook": "# --- BEGIN BEADS INTEGRATION"}[kind]
    if not begins and not ends and prefix not in text:
        return [], None
    if len(begins) != 1 or len(ends) != 1 or text.count(prefix) != 1 or begins[0].end() >= ends[0].start():
        return [], "malformed, duplicate or unsupported " + kind + " markers"
    start, finish = begins[0].start(), ends[0].end()
    return [{"startLine": text.count("\n", 0, start) + 1, "endLine": text.count("\n", 0, finish) + 1,
             "start": start, "end": finish}], None


def unique_object(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError("duplicate JSON key")
        result[key] = value
    return result


def hook_config(text, codex=False):
    data = json.loads(text, object_pairs_hook=unique_object)
    if not isinstance(data, dict) or not isinstance(data.get("hooks", {}), dict):
        raise ValueError("malformed hooks object")
    count, mixed, unknown = 0, False, False
    events = CODEX_EVENTS if codex else ("SessionStart", "PreCompact")
    for event, entries in data.get("hooks", {}).items():
        if not isinstance(entries, list):
            raise ValueError("malformed hook event")
        for entry in entries:
            if not isinstance(entry, dict) or not isinstance(entry.get("hooks"), list) or not entry["hooks"]:
                raise ValueError("malformed or empty hook entry")
            managed = 0
            for command in entry["hooks"]:
                if not isinstance(command, dict) or not isinstance(command.get("command"), str):
                    raise ValueError("malformed hook command")
                value = command["command"]
                match = value.startswith("bd codex-hook ") if codex else value in CLAUDE_COMMANDS
                if match and event in events:
                    if command.get("type") != "command":
                        raise ValueError("ambiguous hook command type")
                    managed += 1
                elif "bd " in value:
                    unknown = True
            count += managed
            mixed = mixed or (0 < managed < len(entry["hooks"]))
    return count, mixed, unknown, "hooks" in data


def bounded_tree(root, relative):
    base = root / relative
    if not base.exists():
        return set(), []
    problems, entries = [], set()
    if base.is_symlink() or not base.is_dir():
        return entries, [relative + ": expected an ordinary directory"]
    for directory, names, files in os.walk(base, followlinks=False):
        if len(entries) + len(names) + len(files) > MAX_HOOK_FILES:
            problems.append(relative + ": generated tree exceeds entry bound")
            break
        current = Path(directory)
        for name in names + files:
            path = current / name
            item = path.relative_to(root).as_posix()
            entries.add(item)
            if path.is_symlink():
                problems.append(item + ": linked generated-tree entry")
    return entries, problems


class Inventory:
    def __init__(self, root):
        self.root = root
        self.rows = {}
        self.text = {}

    def read(self, name):
        if name in self.rows:
            return self.rows[name]
        path = self.root / name
        row = {"path": name, "kind": "missing", "sha256": None}
        self.rows[name] = row
        try:
            canonical = path.resolve(strict=False)
            if not canonical.is_relative_to(self.root):
                raise ValueError("out-of-repository target")
            row["canonical"] = str(canonical)
            linked = any(p.is_symlink() for p in (path, *path.parents) if p != self.root and p.is_relative_to(self.root))
            if linked:
                row["problem"] = "symlink mutation footprint is unsupported"
            if not path.exists():
                if path.is_symlink():
                    raise ValueError("dangling symlink")
                return row
            info = path.stat()
            row.update(kind="file", mode=stat.S_IMODE(info.st_mode), links=info.st_nlink)
            if not stat.S_ISREG(info.st_mode):
                raise ValueError("non-regular file")
            if info.st_nlink != 1:
                row["problem"] = "hardlinked mutation footprint is unsupported"
            if info.st_size > MAX_BYTES:
                raise ValueError("file exceeds byte bound")
            raw = path.read_bytes()
            if len(raw) > MAX_BYTES:
                raise ValueError("file exceeds byte bound")
            row.update(sha256=digest(raw), bytes=len(raw))
            self.text[name] = raw.decode("utf-8", errors="strict")
        except (OSError, RuntimeError, ValueError) as error:
            row["problem"] = str(error) if isinstance(error, ValueError) else "unavailable file identity/content"
        return row

    def files(self):
        groups = {}
        for name, row in self.rows.items():
            key = row.get("canonical", name)
            if key not in groups:
                groups[key] = {**row, "aliases": []}
            groups[key]["aliases"].append(name)
            if row.get("problem"):
                groups[key]["problem"] = row["problem"]
        return sorted(groups.values(), key=lambda item: item["path"])


def inspect_repository(repository):
    if any(os.environ.get(key) for key in ("GIT_DIR", "GIT_WORK_TREE", "GIT_COMMON_DIR", "GIT_INDEX_FILE", "GIT_CONFIG_PARAMETERS", "BEADS_DIR")):
        raise ValueError("ambient Git/Beads location overrides are unsupported")
    count = int(os.environ.get("GIT_CONFIG_COUNT", "0"))
    if not 0 <= count <= 32 or any(
        os.environ.get(f"GIT_CONFIG_KEY_{i}", "").lower() not in ("credential.interactive", "credential.guiprompt")
        or os.environ.get(f"GIT_CONFIG_VALUE_{i}", "").lower() not in ("false", "never", "0")
        for i in range(count)
    ):
        raise ValueError("ambient Git config override is unsupported")
    root = Path(repository).expanduser().resolve(strict=True)
    if root != Path(git(root, "rev-parse", "--show-toplevel")).resolve():
        raise ValueError("select the exact repository root, not a subdirectory")
    inventory = Inventory(root)
    issues = []
    config = git(root, "config", "--local", "--no-includes", "--name-only", "--get-regexp", r"^(include.*\.path|extensions\.worktreeconfig)$", allowed=(0, 1))
    if config:
        issues.append("local Git includes/worktree config are unsupported")
    git_dir = Path(git(root, "rev-parse", "--absolute-git-dir"))
    if (root / ".git").is_symlink() or not (root / ".git").is_dir() or git_dir.resolve() != root / ".git" or (git_dir / "worktrees").exists():
        issues.append("shared, redirected or linked Git administration is unsupported")
    config_row = inventory.read(".git/config")
    if config_row.get("problem"):
        issues.append(".git/config: " + config_row["problem"])
    if (root / ".beads").is_symlink() or os.path.lexists(root / ".beads/redirect"):
        issues.append("linked or redirected Beads storage: no integration removal proposed")
    tool = bd_probe()
    if not tool.get("supported"):
        issues.append("native removal is verified only for bd 1.2.2 with matching help")
    residuals, actions = [], []

    def action(name, paths, needed, effects, reasons):
        for filename in paths:
            row = inventory.read(filename)
            if row.get("problem"):
                reasons.append(filename + ": " + row["problem"])
        reasons = list(dict.fromkeys([*issues, *reasons]))
        env_binary = tool.get("envExecutable") or shutil.which("env")
        if not env_binary:
            reasons.append("env executable with --chdir support is unavailable")
        status = "blocked" if reasons else "ready" if needed else "clean"
        argv = [str(Path(env_binary).resolve()) if env_binary else "env", "--chdir=" + str(root),
                "BD_DISABLE_METRICS=1", "BD_DISABLE_EVENT_FLUSH=1", tool.get("executable", "bd"),
                "-C", str(root), "--sandbox"]
        recipe = name.removesuffix("-native")
        argv += ["hooks", "uninstall"] if recipe == "hooks" else ["setup", recipe, "--remove", "--global=false"]
        actions.append({"id": name, "mechanism": "bd-native", "status": status, "argv": argv if status == "ready" else None,
                        "effects": effects, "reasons": reasons, "requires": ["source scope", "backup/recovery evidence", "fresh per-command confirmation", "post-command verification"]})

    ranges = {}
    for filename in ("AGENTS.md", "CLAUDE.md"):
        row = inventory.read(filename)
        for kind in ("general", "codex"):
            spans, error = block_ranges(inventory.text.get(filename, ""), kind)
            ranges[filename, kind] = spans
            if error:
                row["problem"] = error
            if spans:
                row[kind + "Blocks"] = [{k: v for k, v in span.items() if k.endswith("Line")} for span in spans]

    agents_effects, agents_reasons = [], [*issues]
    for kind, operation in (("general", "remove exact general managed block"), ("codex", "remove exact Codex managed block")):
        if ranges["AGENTS.md", kind]:
            agents_effects.append({"path": "AGENTS.md", "operation": operation,
                                   "lines": inventory.rows["AGENTS.md"].get(kind + "Blocks")})
    if inventory.rows["AGENTS.md"].get("problem"):
        agents_reasons.append("AGENTS.md: " + inventory.rows["AGENTS.md"]["problem"])
    agents_status = "blocked" if agents_reasons else "ready" if agents_effects else "clean"
    actions.append({"id": "agents-blocks", "mechanism": "confirmed-native-edit", "status": agents_status,
                    "argv": None, "effects": agents_effects, "reasons": list(dict.fromkeys(agents_reasons)),
                    "requires": ["shared replacement guidance confirmed", "source scope", "backup/recovery evidence", "fresh confirmation", "exact old/new preview", "post-edit verification"]})

    claude_paths = ["CLAUDE.md", ".claude/settings.json", ".claude/settings.local.json"]
    effects, reasons = [], []
    needed = bool(ranges["CLAUDE.md", "general"])
    if needed:
        effects.append({"path": "CLAUDE.md", "operation": "remove general managed block", "lines": inventory.rows["CLAUDE.md"].get("generalBlocks")})
    for filename in claude_paths[1:]:
        row = inventory.read(filename)
        if filename in inventory.text:
            try:
                count, _, unknown, has_hooks = hook_config(inventory.text[filename])
                row["managedCommands"] = count
                needed = needed or count > 0
                if has_hooks:
                    effects.append({"path": filename, "operation": "rewrite hook JSON; remove exact bd prime commands, preserve siblings", "removedCommands": count})
                if unknown:
                    residuals.append({"path": filename, "reason": "nonstandard bd hook commands remain"})
            except ValueError:
                reasons.append(filename + ": malformed or ambiguous hook JSON")
    action("claude", claude_paths, needed, effects, reasons)

    codex_paths = ["AGENTS.md", ".codex/config.toml", ".codex/hooks.json", *TEMPLATE_HASHES]
    effects, reasons = [], []
    needed = bool(ranges["AGENTS.md", "codex"])
    if needed:
        effects.append({"path": "AGENTS.md", "operation": "remove Codex managed block only", "lines": inventory.rows["AGENTS.md"].get("codexBlocks")})
    if inventory.read(".codex/config.toml")["kind"] != "missing":
        reasons.append(".codex/config.toml exists: native removal may disable shared hook feature flags; no safe scoped remover")
    for filename, expected in TEMPLATE_HASHES.items():
        row = inventory.read(filename)
        if row["kind"] != "missing":
            needed = True
            if row.get("sha256") != expected:
                reasons.append(filename + ": generated template ownership is unproven")
            effects.append({"path": filename, "operation": "delete exact bd 1.2.2 generated file; prune empty skill ancestors"})
    row = inventory.read(".codex/hooks.json")
    if ".codex/hooks.json" in inventory.text:
        try:
            count, mixed, unknown, _ = hook_config(inventory.text[".codex/hooks.json"], codex=True)
            needed = needed or count > 0
            if mixed:
                reasons.append(".codex/hooks.json: native removal would delete sibling non-Beads commands")
            if unknown:
                reasons.append(".codex/hooks.json: nonstandard bd commands need separate review")
            effects.append({"path": ".codex/hooks.json", "operation": "remove managed entries; delete file if empty, otherwise rewrite JSON", "removedCommands": count})
        except ValueError:
            reasons.append(".codex/hooks.json: malformed or ambiguous hook JSON")
    action("codex-native", codex_paths, needed, effects, reasons)

    generated_effects, generated_reasons = [], [*issues]
    codex_entries, codex_tree_problems = bounded_tree(root, ".codex")
    skill_entries, skill_tree_problems = bounded_tree(root, ".agents/skills/beads")
    generated_reasons.extend(codex_tree_problems + skill_tree_problems)
    expected_codex_entries = {".codex/config.toml", ".codex/hooks.json"}
    expected_skill_entries = {".agents/skills/beads/SKILL.md", ".agents/skills/beads/agents", ".agents/skills/beads/agents/openai.yaml"}
    if codex_entries - expected_codex_entries:
        generated_reasons.append(".codex contains non-generated or unexpected entries")
    if skill_entries - expected_skill_entries:
        generated_reasons.append(".agents/skills/beads contains non-generated or unexpected entries")
    for filename, expected in GENERATED_CODEX_HASHES.items():
        row = inventory.read(filename)
        if row["kind"] != "missing":
            generated_effects.append({"path": filename, "operation": "delete exact bd 1.2.2 generated file"})
            if row.get("sha256") != expected:
                generated_reasons.append(filename + ": generated ownership hash mismatch")
    if ranges["AGENTS.md", "codex"]:
        span = ranges["AGENTS.md", "codex"][0]
        block = inventory.text["AGENTS.md"][span["start"]:span["end"]]
        if digest(block.encode()) != GENERATED_CODEX_BLOCK_SHA256:
            generated_reasons.append("AGENTS.md: Codex managed block does not match checked bd 1.2.2 output")
    local_skill = root / ".agents/skills/beads"
    global_skill = Path.home() / ".agents/skills/beads"
    if local_skill.exists() and global_skill.exists():
        local_info, global_info = local_skill.stat(), global_skill.stat()
        if local_skill.resolve() == global_skill.resolve() or (local_info.st_dev, local_info.st_ino) == (global_info.st_dev, global_info.st_ino):
            generated_reasons.append("project generated skill aliases the global skill installation")
    generated_status = "blocked" if generated_reasons else "ready" if generated_effects else "clean"
    actions.append({"id": "codex-generated", "mechanism": "confirmed-exact-delete", "status": generated_status,
                    "argv": None, "effects": generated_effects, "reasons": list(dict.fromkeys(generated_reasons)),
                    "pruneEmptyDirectories": [".codex", ".agents/skills/beads/agents", ".agents/skills/beads", ".agents/skills", ".agents"],
                    "requires": ["agents-blocks selected or Codex block already absent", "source scope", "verified private backup hashes", "fresh confirmation", "one visible exact-file deletion command", "post-delete verification"]})

    effects, reasons, paths, needed = [], [], [], False
    hooks_config = git(root, "config", "--show-scope", "--show-origin", "--get-all", "core.hooksPath", allowed=(0, 1))
    hook_dir = Path(git(root, "rev-parse", "--git-path", "hooks"))
    if not hook_dir.is_absolute():
        hook_dir = root / hook_dir
    if any(not line.startswith("local\t") for line in hooks_config.splitlines()) or len(hooks_config.splitlines()) > 1:
        reasons.append("inherited or multiple hooksPath values: fallback integration cannot be proven safe")
    if not hook_dir.resolve().is_relative_to(root):
        reasons.append("hook directory is outside the selected repository")
    else:
        relative = hook_dir.relative_to(root).as_posix()
        if relative not in (".git/hooks", ".beads/hooks", ".beads-hooks"):
            reasons.append("custom hooksPath has no verified removal contract")
        resets = relative in (".beads/hooks", ".beads-hooks")
        literal_hook_path = hooks_config.split("\t")[-1] if hooks_config else ""
        if resets and literal_hook_path not in (relative, str(root / relative)):
            reasons.append("noncanonical hooksPath spelling: native reset is not verified")
        dirs = list(dict.fromkeys([relative, ".git/hooks"]))
        for directory in dirs:
            directory_path = root / directory
            if any(p.is_symlink() for p in (directory_path, *directory_path.parents) if p != root and p.is_relative_to(root)):
                reasons.append(directory + ": linked hooks directory")
                continue
            if directory_path.exists() and not directory_path.is_dir():
                reasons.append(directory + ": invalid hook directory")
                continue
            entries = sorted(directory_path.iterdir()) if directory_path.is_dir() else []
            if len(entries) > MAX_HOOK_FILES:
                reasons.append(directory + ": hook inventory exceeds bound")
                continue
            for entry in entries:
                filename = entry.relative_to(root).as_posix()
                paths.append(filename)
                row = inventory.read(filename)
                text = inventory.text.get(filename, "")
                if entry.name.endswith((".old", ".backup")):
                    reasons.append(filename + ": chain/backup may become unreachable")
                if directory != relative:
                    if resets and not entry.name.endswith(".sample"):
                        reasons.append(filename + ": unsetting hooksPath would activate an existing fallback hook")
                    continue
                spans, error = block_ranges(text, "hook")
                if error or (not spans and any(marker in text for marker in ("# bd-shim ", "# bd-hooks-version:", "# bd (beads)"))):
                    reasons.append(filename + ": malformed/legacy hook removal is unsupported")
                if spans and entry.name in HOOK_NAMES:
                    needed = True
                    remaining = text[:spans[0]["start"]] + text[spans[0]["end"]:]
                    pure = remaining.strip() in ("", "#!/bin/sh", "#!/usr/bin/env sh")
                    effects.append({"path": filename, "operation": "delete pure Beads hook" if pure else "strip managed block; preserve project hook"})
                    if resets and not pure:
                        reasons.append(filename + ": unsetting hooksPath would disable preserved project checks")
                elif resets:
                    reasons.append(filename + ": unsetting hooksPath would strand non-managed content")
                elif spans:
                    residuals.append({"path": filename, "reason": "hook is outside the owning tool removal set"})
        if resets:
            needed = True
            effects.append({"path": ".git/config", "operation": "unset local core.hooksPath; reactivate default .git/hooks"})
    action("hooks", paths, needed, effects, reasons)

    ignore_paths = [".gitignore", ".beads/.gitignore", ".beads/interactions.jsonl"]
    ignore_reasons = [*issues]
    for filename in ignore_paths:
        row = inventory.read(filename)
        if row.get("problem"):
            ignore_reasons.append(filename + ": " + row["problem"])
    root_ignore = inventory.text.get(".gitignore", "")
    beads_ignore = inventory.text.get(".beads/.gitignore", "")
    rule_present = any(line.strip() == IGNORE_INTERACTIONS for line in root_ignore.splitlines())
    if any(line.lstrip().startswith("!") for line in beads_ignore.splitlines()):
        ignore_reasons.append(".beads/.gitignore contains negation rules; ignore precedence needs manual review")
    tracked = bool(git(root, "ls-files", "--", ".beads/interactions.jsonl", allowed=(0, 1)))
    if tracked and inventory.rows[".beads/interactions.jsonl"]["kind"] == "missing":
        ignore_reasons.append("tracked interactions file is absent; local retention cannot be proven")
    ignore_effects = []
    interactions_present = inventory.rows[".beads/interactions.jsonl"]["kind"] != "missing"
    if not rule_present and (tracked or interactions_present):
        ignore_effects.append({"path": ".gitignore", "operation": "add anchored ignore rule", "rule": IGNORE_INTERACTIONS})
    if tracked:
        ignore_effects.append({"path": ".beads/interactions.jsonl", "operation": "remove from Git index only; retain local file"})
    ignore_status = "blocked" if ignore_reasons else "ready" if ignore_effects else "clean"
    actions.append({"id": "interactions-ignore", "mechanism": "confirmed-native-edit-and-git-index", "status": ignore_status,
                    "argv": None, "indexArgv": ["git", "-C", str(root), "rm", "--cached", "--", ".beads/interactions.jsonl"] if tracked else None,
                    "ignoreRule": IGNORE_INTERACTIONS, "effects": ignore_effects, "reasons": list(dict.fromkeys(ignore_reasons)),
                    "requires": ["source scope", "backup/recovery evidence", "fresh confirmation before index mutation", "git check-ignore --no-index cites root rule", "local file retained", "post-change status verification"]})

    for name in (".beads/recipes.toml", ".gemini/settings.json", ".cursor/rules/beads.mdc", ".github/copilot-instructions.md", ".aider.conf.yml"):
        row = inventory.read(name)
        if row["kind"] != "missing" or row.get("problem"):
            residuals.append({"path": name, "reason": "other/custom client integration: inspection only, no verified removal action"})
    report = {"schemaVersion": "beads-integration-cleanup/v1", "repository": str(root), "bd": tool,
              "files": inventory.files(), "actions": actions, "residuals": residuals,
              "hooksConfig": hooks_config, "readOnly": True, "inspectorSha256": digest(Path(__file__).read_bytes())}
    report["fingerprint"] = digest(json.dumps(report, sort_keys=True).encode())
    return report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", required=True, help="exact repository root (never recursive)")
    parser.add_argument("--expect", help="require unchanged prior fingerprint; not an approval token")
    parser.add_argument("--action", choices=("agents-blocks", "claude", "codex-native", "codex-generated", "hooks", "interactions-ignore"), help="require this proposal to be ready; never execute it")
    args = parser.parse_args()
    try:
        report = inspect_repository(args.repo)
        if args.expect and args.expect != report["fingerprint"]:
            raise ValueError("stale preview: inventory changed; inspect and confirm again")
        if args.action and next(a for a in report["actions"] if a["id"] == args.action)["status"] != "ready":
            raise ValueError("selected action is not ready; no command authorized")
        print(json.dumps(report, indent=2, ensure_ascii=True))
        return 0
    except ValueError as error:
        print(json.dumps({"error": str(error), "readOnly": True}))
        return 2
    except (OSError, RuntimeError, subprocess.SubprocessError):
        print(json.dumps({"error": "inspection unavailable; no action may run", "readOnly": True}))
        return 2


if __name__ == "__main__":
    sys.exit(main())
